### ISSUE TITLE
TFM issue in TeXLive 2016

### ISSUE THREAD

**Issue by ncihnegn** [clerkma/ptex-ng-dist#3]
Please check the log below:

> This is pTeX-ng, Version 3.14159265 (W32TeX) (preloaded format=platex-ng)
> entering extended mode
> (test-otf-aozora-tate.tex
> pLaTeX2e <2016/06/10u01> (based on LaTeX2e <2016/03/31> patch level 1)
> Babel <3.9r> and hyphenation patterns for 3 language(s) loaded.
> ! Font \yumin=ot:yumin.ttf;vert:upjisr-v not loadable: Metric (TFM) file not fo
> und.
> <to be read again>
>                    \tfont
> l.18 \tfont
>            \yumindb=ot:yumindb.ttf;vert:upjisr-v

**Comment by clerkma** [comment]
更新
